version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin   # Utilisateur admin pour Keycloak
      - KEYCLOAK_ADMIN_PASSWORD=admin  # Mot de passe admin
      - DB_VENDOR=h2
    ports:
      - "9000:8080"
    command: start-dev 
    networks:
      - keycloak-network

  angular-app:
    container_name: frontend
    build: .
    expose:
      - 4200
    ports:
      - 4200:4200
    volumes:
      - ./:/app
    command: npx ng serve --host 0.0.0.0 --poll=2000
    restart: on-failure
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
